version: '3.8'

services:
  uhf-server:
    image: solidpixel/uhf-server:1.2.0-ffmpeg7.0.2-test
    container_name: uhf-server
    restart: unless-stopped
    volumes:
      - ./uhf-data:/var/lib/uhf-server
    working_dir: /uhf-data
    network_mode: host
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - RECORDINGS_DIR=/var/lib/uhf-server/recordings
      - DB_PATH=/var/lib/uhf-server/db.json
      - LOG_LEVEL=INFO
    command: ["uhf-server"]
