version: '3.8'

services:
  uhf-server:
    build:
      context: .
      dockerfile: Dockerfile.uhf
    container_name: uhf-server
    restart: unless-stopped
    volumes:
      - ./uhf-data:/var/lib/uhf-server
    network_mode: host
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=78000
      - RECORDINGS_DIR=/var/lib/uhf-server/recordings
      - DB_PATH=/var/lib/uhf-server/db.json
      - LOG_LEVEL=INFO
      
