version: '3.8'

services:
  uhf-server:
    build:
      context: .
      dockerfile: Dockerfile.uhf
    container_name: uhf-server
    restart: unless-stopped
    volumes:
      - ./uhf-data:/var/lib/uhf-server
    network_mode: host
    env_file:
      - stack.env
