services:

  uhf-server:

    image: solidpixel/uhf-server:uhf-2.0.0-ffmpeg7.1.1-d1
    container_name: uhf-server
    restart: unless-stopped

    volumes:
      # Persist recordings and database
      - ./uhf-data:/var/lib/uhf-server

      # OPTIONAL: store recordings in a different location
      # Uncomment the line below IN ADDITION to the one above
      # This overrides only /recordings inside the container
      # - ./uhf-recordings:/var/lib/uhf-server/recordings

    ports:
      - 8000:8000  # <HOST>:<CONTAINER>

    # Optional container environment config
    environment:
      - ENABLE_COMMERCIAL_DETECTION=${ENABLE_COMMERCIAL_DETECTION:-false}  # set true for commercial detection
      - PASSWORD=${PASSWORD:-}
      # Uncomment below to customize internal container settings (usually not needed)
      # - API_HOST=0.0.0.0
      # - API_PORT=8000
      # - RECORDINGS_DIR=/var/lib/uhf-server/recordings
      # - DB_PATH=/var/lib/uhf-server/db.json
      # - LOG_LEVEL=INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

    # Command with conditional flags
    # !!! Do not modify this unless you know what you're doing !!!
    command:
      - bash
      - -c
      - |
          commercial_detection="$${ENABLE_COMMERCIAL_DETECTION:-}"
          password="$${PASSWORD:-}"
          unset ENABLE_COMMERCIAL_DETECTION PASSWORD
          args=(uhf-server)
          if [[ "$$commercial_detection" == "true" ]]; then
            args+=(--enable-commercial-detection)
          fi
          if [[ -n "$$password" ]]; then
            args+=(--password "$$password")
          fi
          exec "$${args[@]}"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/server/stats"] # update URL if API_PORT changes
      interval: 30s
      timeout: 5s
      retries: 3
