version: '3.8'

services:
  uhf-server:
    image: solidpixel/uhf-server:1.1.0
    container_name: uhf-server
    restart: unless-stopped
    volumes:
      - ./uhf-data:/var/lib/uhf-server
    working_dir: /uhf-data
    network_mode: host
    command: ["uhf-server", "--port", "8000"] # optionally change the port in case it's already in use by something else
