name: Build & Publish Multi-Arch Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from changelog
        id: version
        run: |
          VERSION=$(grep -A1 "Version " README.md | head -n1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" || echo "latest")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          if [ "${{ steps.version.outputs.version }}" != "latest" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git tag -f "v${{ steps.version.outputs.version }}"
            git push origin "v${{ steps.version.outputs.version }}" --force
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.uhf
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            solidpixel/uhf-server:latest
            solidpixel/uhf-server:${{ steps.version.outputs.version }}
