name: Build & Publish Multi-Arch Docker Image

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_pr:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.pr_info.outputs.skip_build }}
    steps:
      - name: Get PR info
        id: pr_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE=$(gh api /repos/${{ github.repository }}/commits/${{ github.sha }}/pulls --jq '.[0].title')
          if [[ "$PR_TITLE" == *"[skip_build]"* ]]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

  tag:
    needs: check_pr
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    outputs:
      uhf_version: ${{ steps.version.outputs.uhf_version }}
      ffmpeg_version: ${{ steps.version.outputs.ffmpeg_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get versions
        id: version
        run: |
          # Get UHF version from badge in README.md
          UHF_VERSION=$(grep "uhf_server-" README.md | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" || echo "latest")
          
          # Get FFmpeg version from git checkout
          FFMPEG_VERSION=$(grep "git checkout n" Dockerfile.uhf | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" || echo "")
          
          echo "uhf_version=$UHF_VERSION" >> $GITHUB_OUTPUT
          echo "ffmpeg_version=$FFMPEG_VERSION" >> $GITHUB_OUTPUT
          
      - name: Create and push tag
        run: |
          if [ "${{ steps.version.outputs.uhf_version }}" != "latest" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git tag -f "v${{ steps.version.outputs.uhf_version }}-ffmpeg${{ steps.version.outputs.ffmpeg_version }}"
            git push origin "v${{ steps.version.outputs.uhf_version }}-ffmpeg${{ steps.version.outputs.ffmpeg_version }}" --force
          fi

  docker:
    needs: [check_pr, tag]
    if: |
      needs.check_pr.outputs.skip_build != 'true' &&
      github.event_name == 'push' && 
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.uhf
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            solidpixel/uhf-server:latest
            solidpixel/uhf-server:${{ needs.tag.outputs.uhf_version }}-ffmpeg${{ needs.tag.outputs.ffmpeg_version }}
